version: "3"
services:
  proiectcloud:
    image: proiectcloud
    ports:
      - "8080:8080"
    networks:
      - boot-mysql
    depends_on:
      - mysql
 
  mysql:
    image: mysql:8
    networks:
      - boot-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=proiectcloud

networks:
  boot-mysql: